### PR TITLE
#146 - Update dependencies

### PR DESCRIPTION
**Pull request by reckart**
- Updated basically all dependencies in the package.json file
- Set minimum required node version to 16 since that is what some of the updated dependencies require

### CODE REVIEW

**Comment by reckart** [comment]
@tilgovi @BigBlueHat @Treora I have done pretty radical update of dependencies here. Looks like the build process is happy. Anybody care to have a look at these changes since I'm not really too familiar with the tooling used by Apache Annotator. I still think switching to plain npm would be better these days (and drop lerna and yarn). Also I thing esbuild instead of webpack would be nice :)

**Comment by tilgovi** [comment]
Looks great. I will make a PR to drop Yarn for NPM, because I don't think there is any benefit to continuing to use Yarn (especially not without the advanced features).

Can you say anything about the non-dependency changes here? The ajv invocation and the lerna.json?

**Comment by tilgovi** [comment]
I'm guessing useWorkspaces is just gone these days.

I started looking at updating Lerna and trying out Nx a while back. I'll see where my branch got and try to see whether it's worth doing anything with these tools still.

Thanks again for looking at this.

**Comment by reckart** [comment]
Lerna said that `useWorkspaces` no longer exists.

And `auto` was no longer a valid value for `schemaId` in `Ajv`. I considered specifying a particular schema version, but since the parameter is optional and the build works without specifying a version, I left it without the `schemaId`.

**Review by tilgovi — APPROVED** [review]
Sounds good!

**Pull request merged**
