### PR TITLE
Add Travis-CI for test running

### LINKED ISSUE #34: Multiple packages have conflicting node version dependency
i was unable to proceed further than yarn install, i'm interested to contribute to the project but unable to setup the environment. i tried on node version @6.11.5 and yarn @1.5.1
```
error @shellscape/koa-static@4.0.4: The engine "node" is incompatible with this module. Expected version ">= 7.6.0".
error An unexpected error occurred: "Found incompatible module".
```
And when i try with node 7.6.0, i get below error,
screenshot 25

### LINKED ISSUE #36: Continuous Integration
I've started a basic [travis-ci.org](https://travis-ci.org/) setup via [a personal fork](https://travis-ci.org/BigBlueHat/incubator-annotator).

This has raised a few questions:
 - do we want to use travis-ci?
   - I've no preference; Infra's set it up for others before...but also may not care in practice
 - @tilgovi mentioned that the top-level package needs node 8+ whereas the `packages/` need node 6+
   - however...I've not been able to sort configuring travis in such away as to accommodate that...

Here's what I've got so far:
 - GitHub branch: https://github.com/BigBlueHat/incubator-annotator/tree/travis-ci
 - Latest Travis run: https://travis-ci.org/BigBlueHat/incubator-annotator

My last attempt includes using `node` as the `node_js` version via `.travis.yml` and attempting to use `.nvmrc` files for local `packages/` folders. Turns out Travis doesn't check all those...

There's also the question of narrowing the test runs to just each individual package.

Anyhow. It's doable, but there's a lot more to do...

### PR DESCRIPTION
**Pull request by BigBlueHat**
Pretty sure this is ready. 😁 

Successful test run here:
https://travis-ci.org/BigBlueHat/incubator-annotator

We'll probably need help from ASF Infra to get the rest of the bits in place:
https://travis-ci.org/apache/incubator-annotator

Fixes #36 
Fixes #35
Fixes #34

### CODE REVIEW

**Comment by tilgovi** [comment]
@BigBlueHat I agree with that. We can specify the node version in the Travis CI configuration, though, rather than in a .nvmrc file, no?

**Comment by tilgovi** [comment]
Doing it in the Travis configuration, we can even tell Travis to run it under 6, 8, and 10.

**Comment by BigBlueHat** [comment]
I'll try that again, but iirc [that approach](https://docs.travis-ci.com/user/languages/javascript-with-nodejs#specifying-nodejs-versions) failed for me in some way so I switched to using `nvm` on travis ([per their advice](https://docs.travis-ci.com/user/languages/javascript-with-nodejs#specifying-nodejs-versions-using-nvmrc)).

It might have been that I wanted devs to be able to run mutli-version tests (as their option) locally--which afaik can't be done with just a travis config.

I'll tweak my copy and see what happens. 😉

**Comment by BigBlueHat** [comment]
@tilgovi I found the error from earlier build tests:
https://travis-ci.org/BigBlueHat/incubator-annotator/jobs/394262379#L474

Seems yarn install fails on node 6.x because of the top-level package.json's declaration of `>= 8.0.0`:
```
error @annotator/annotator@: The engine "node" is incompatible with this module. Expected version ">=8.0.0".
error An unexpected error occurred: "Found incompatible module".
```

Thoughts?

**Comment by tilgovi** [comment]
If that's the case I'm sure I did it for a reason and we can try to relax it more in the future if we want. The top-level package doesn't "ship" so it's not a requirement to have Node 8 except for development, which I think is okay for now.

Can we use the Travis configuration to specify testing under 8 and 10 for now, and we'll aim for getting the development requirements down to 6 so that we can build and test in the same environment back to the earliest LTS we support?

**Comment by BigBlueHat** [comment]
@tilgovi done. Here's how Travis feels about these changes:
https://travis-ci.org/BigBlueHat/incubator-annotator

Essentially, we're back to tests failing under node 6 because yarn won't install the main `annotator/annotator` package (because it's `engine` in `package.json` doesn't match the environment), but everything else tests fine. Maybe there's a `yarn --do-it-anyway` flag...?

**Comment by BigBlueHat** [comment]
Well. It's called `yarn install --ignore-engines`, but that should do the trick. 😁 Now to get travis (and only travis) to use that...

**Comment by tilgovi** [comment]
I would just leave out 6 right now or mark it as allowed to fail and we'll try to push our development requirements back down to 6.

**Comment by BigBlueHat** [comment]
Yeah. It seems adding `--ignore-engines` didn't do the trick...they just re-run yarn without it...
https://travis-ci.org/BigBlueHat/incubator-annotator/jobs/436325051#L475

I'll drop 6 in this PR, and then merge it. We'll then need to get infra to setup Travis integration (afaik).

**Pull request merged**
