### PR TITLE
Add remote URL fetching to `yarn validate --url`

### LINKED ISSUE #33: Make test `--url` parameter work with remote URLs (not just local files)
Maybe use [requests](https://www.npmjs.com/package/requests) or [axios](https://www.npmjs.com/package/axios) or Node's [http](https://nodejs.org/api/http.html#http_http).

Preference?

### PR DESCRIPTION
**Pull request by jccr**
Fixes #33

### CODE REVIEW

**Comment by BigBlueHat** [comment]
This looks great @jccr!

Could you update the README with an example of using it with a URL?

You could point to https://github.com/w3c/web-annotation-tests/blob/master/tools/samples/correct/anno1.json ([raw](https://raw.githubusercontent.com/w3c/web-annotation-tests/master/tools/samples/correct/anno1.json)) for a correct/passing example and/or https://github.com/w3c/web-annotation-tests/blob/master/tools/samples/incorrect/anno1.json ([raw](https://raw.githubusercontent.com/w3c/web-annotation-tests/master/tools/samples/incorrect/anno1.json)) for a broken one.

**Comment by BigBlueHat** [comment]
@tilgovi @niq does @jccr need to sign an ICLA before we merge this? https://www.apache.org/licenses/#clas

This question would also pertain to @JakeHartnell's contributions here and the website https://github.com/apache/incubator-annotator-website/graphs/contributors

**Comment by niq** [comment]
> On 12 Oct 2018, at 15:22, BigBlueHat <notifications@github.com> wrote:
> 
> @tilgovi @niq does @jccr need to sign an ICLA before we merge this? https://www.apache.org/licenses/#clas

No.  We can (and regularly do) accept small patches from third-parties who contribute them.

It might be appropriate if (and only if) jccr is taking a longer-term interest and likely to
contribute regularly (or at least semi-regularly).  But that would be a matter to raise at apache,
not github.

-- 
Nick Kew

**Comment by BigBlueHat** [comment]
Thanks for this contribution @jccr! We look forward to many more. 😉

**Pull request merged**
